// Defines the "target server", which is the server
// that we're going to hack. In this case, it's "INSERT_SERVER_NAME"
var target = "harakiri-sushi"; //max-hardware

// Defines how much money a server should have before we hack it
// In this case, it is set to 75% of the server's max money
//This is commented out to save RAM space
//var moneyThresh = getServerMaxMoney(target) * 0.75;
var moneyThresh = 75000000;

// Defines the maximum security level the target server can
// have. If the target's security level is higher than this,
// we'll weaken it before doing anything else
//This is commented out to save RAM space
//var securityThresh = getServerMinSecurityLevel(target) + 5;
var securityThresh = 10;

// If we have the BruteSSH.exe program, use it to open the SSH Port
// on the target server
/* //ALL COMMENTED TO SAVE RAM SPACE
if (fileExists("BruteSSH.exe", "home")) {
	brutessh(target);
}

// If we have the FTPCrack.exe program, use it to open the FTP Port
// on the target server
if (fileExists("FTPCrack.exe", "home")) {
	ftpcrack(target);
}

// If we have the HTTPWorm.exe program, use it to open the HTTP Port
// on the target server
if (fileExists("HTTPWorm.exe", "home")) {
	httpworm(target);
}

// If we have the SQLInject.exe program, use it to open the SQL Port
// on the target server
if (fileExists("SQLInject.exe", "home")) {
	sqlinject(target);
}

// If we have the relaySMTP.exe program, use it to open the SMTP Port
// on the target server
if (fileExists("relaySMTP.exe", "home")) {
	relaysmtp(target);
}
*/
// Get root access to target server
//Commented to save RAM SPACE
//nuke(target);

// Infinite loop that continously hacks/grows/weakens the target server
while (true) {
	//Code to save 0.2 RAM Space
	var moneynow = getServerMoneyAvailable(target);
	var securitynow = getServerSecurityLevel(target)
	if (securitynow > securityThresh) {
		// If the server's security level is above our threshold, weaken it
		weaken(target);
	} else if (moneynow < moneyThresh) {
		// If the server's money is less than our threshold, grow it
		grow(target);
	} else {
		// Otherwise, hack it
		hack(target);
	}
}
